site_name: Islandora Enterprise (ISLE)
site_description: Documentation for Islandora Enterprise (ISLE)

site_dir: site
docs_dir: docs

theme:
  name: 'material'

extra:
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'account_balance'

pages:
- Home: index.md
- About: about.md
- Glossary of Terms and Variables: glossary.md
- Installation Start Here: install_start_here.md
- 'Installation':
  - 'Host Server Specifications': '01_installation_host_server/host_server_system_specifications.md'
  - 'Install ISLE Host Server Dependencies on CentOS': '01_installation_host_server/install_on_centos.md'
  - 'Install ISLE Host Server Dependencies on Ubuntu': '01_installation_host_server/install_on_ubuntu.md'
  - 'Docker for Mac': '01_installation_host_server/install_docker_for_mac.md'
  - 'Docker for Windows': '01_installation_host_server/install_docker_for_windows.md'
  - 'Vagrant & VirtualBox on MacOS': '01_installation_host_server/install_macos_vagrant.md'
- 'Installation - Test (isle.localdomain)':
  - 'Example User Story': '02_installation_test/ild_example_user_story.md'
  - 'Test Site Installation Guide': '02_installation_test/ild_installation_guide.md'
  - 'Test Site Resources': '02_installation_test/ild_resources.md'
- 'Installation - New Site':
  - 'Example User Story': '03_installation_new_site/new_site_example_user_story.md'
  - 'New Site Installation Guide - w/ Single ISLE Environment': '03_installation_new_site/new_site_installation_guide_single.md'
  - 'New Site Installation Guide - w/ multiple ISLE Environments': '03_installation_new_site/new_site_installation_guide_multi.md'
- 'Installation - Migration':
  - 'Example User Story': '04_installation_migration/migration_example_user_story.md'
  - 'Installation Guide': '04_installation_migration/migration_installation_guide.md'
  - 'Export Checklist': '04_installation_migration/migration_export_checklist.md'
  - 'Merge Checklist': '04_installation_migration/migration_merge_checklist.md'
  - 'Docker Composer Edit Checklist': '04_installation_migration/migration_docker_compose_edit_checklist.md'
  - 'Reindex Process': '04_installation_migration/migration_reindex_process.md'
- 'Developer Docs':
  - 'Contributing to Project': '05_developer_docs/dev_contributing_to_project.md'
  - 'Documentation Overview': '05_developer_docs/dev_documentation_overview.md'
  - 'Documentation Editing - Online': '05_developer_docs/dev_documentation_editing_online.md'
  - 'Documentation Editing - Local': '05_developer_docs/dev_documentation_editing_local.md'
  - 'Installing Mkdocs': '05_developer_docs/dev_documentation_mkdocs.md'
  - 'About Maintainers': '05_developer_docs/dev_about_maintainers.md'
  - 'About Project': '05_developer_docs/dev_about_project.md'
  - 'Release process': '05_developer_docs/dev_release_process.md'
  - 'Example User Story': '05_developer_docs/dev_example_user_story.md'
  - 'Policies': '05_developer_docs/dev_policies.md'
  - 'Build Guide': '05_developer_docs/dev_build_guide.md'
  - 'Testing Guide': '05_developer_docs/dev_testing_guide.md'
  - 'Pushing images to Dockerhub Guide': '05_developer_docs/dev_push_images_dockerhub.md'
  - 'Announcements of new releases': '05_developer_docs/dev_announcements_releases.md'
  - 'Ansible Guide': '05_developer_docs/dev_ansible_guide.md'
- 'Specifications':
  - 'Dockerfiles': '06_specifications/specs_dockerfiles.md'
  - 'Docker Containers & Images': '06_specifications/specs_docker_containers_images.md'
  - 'Diagram of network and connections': '06_specifications/specs_diagram_network.md'
  - 'Supported ISLE Software Matrix': '06_specifications/specs_supported_software_matrix.md'
  - 'Supported Drupal Modules on Test Site Matrix': '06_specifications/specs_supported_drupal_modules_matrix.md'
