version: '2'
labels:
  org.label-schema.version: "Production - Enduser Institution"
  org.label-schema.description: "Enduser Institution docker-compose.yml for use with the official ISLE Dockerhub images and pre-existing production Enduser Institution configurations and data."
  org.label-schema.license: "Apache-2.0"
  org.label-schema.vcs-url: "EDIT - ISLE enduser Github repositiory information here" # edit here and remove comment e.g. org.label-schema.vcs-url: "git@github.com:Islandora-Collaboration-Group/ISLE.git"
  org.label-schema.vendor: "EDIT - ISLE enduser Institution information here" # edit here and remove comment
  org.label-schema.schema-version: "1.0"

services:
  mysql:
    image: islandoracollabgroup/isle-mysql:alpha2
    environment:
      - MYSQL_ROOT_PASSWORD= # edit here and remove comment
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initscripts:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./isle_production_data_storage/data/mysql:/var/lib/mysql # edit here and remove comment
      - ./isle_production_data_storage/data/mysql/log:/var/log/mysql # edit here and remove comment
    container_name: isle-mysql-prodname # rename container to indicate type e.g. prod, stage, dev or version here and remove comment
    extra_hosts:
      - "isle-prod-site.institution:IP address of Dockerhost server" # edit here and remove comment

  fedora:
    image: islandoracollabgroup/isle-fedora:alpha2
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8777:80"
      - "8778:443"
    tty: true
    depends_on:
      - mysql
    volumes:
    - ./fedora/apache/site.conf:/etc/apache2/sites-available/site.conf # make edits as necessary
    - ./fedora/fedora/fedora.fcfg:/usr/local/fedora/server/config/fedora.fcfg # edit lines: 562 to change fedora_admin db username (if necessary) & 598 (necessary) for fedora_admin db password
    - ./fedora/fedora/repository-policies/default:/usr/local/fedora/data/fedora-xacml-policies/repository-policies/default # may need to add Docker Host Server IP(s) to default/deny-apim-if-not-localhost.xml
    - ./fedora/fedora/repository-policies/islandora:/usr/local/fedora/data/fedora-xacml-policies/repository-policies/islandora
    - ./fedora/fedora/fedora-users.xml:/usr/local/fedora/server/config/fedora-users.xml # edit to add appropriate users and passwords
    - ./fedora/fedora/filter-drupal.xml:/usr/local/fedora/server/config/filter-drupal.xml # edit to add appropriate Drupal site(s) along with mysql user(s) and password(s)
    - ./fedora/gsearch/fedoragsearch.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/fedoragsearch.properties # edit line 7 to add fgsAdmin password
    - ./fedora/gsearch/fgsconfig-basic-configForIslandora.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/fgsconfig-basic-configForIslandora.properties # edit lines: 26 to add fgsAdmin password, 67 to add fedoraAdmin password
    - ./fedora/gsearch/fgsconfigObjects.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/fgsconfigObjects.properties # edit line 15 to add fedoraAdmin password
    - ./fedora/gsearch/repository.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/repository/FgsRepos/repository.properties # edit line 7 to add fedoraAdmin password
    - ./fedora/tomcat/server.xml:/usr/local/tomcat/conf/server.xml # edit for SSL additions
    - ./fedora/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml # edit lines: 45 & 48 to add appropriate passwords
    - ./isle_production_data_storage/data/fedora/data:/usr/local/fedora/data
    - ./isle_production_data_storage/data/fedora/log/fedora:/usr/local/fedora/server/logs
    - ./isle_production_data_storage/data/fedora/log/tomcat:/usr/local/tomcat/logs
    - ./isle_production_data_storage/data/fedora/log/apache:/var/log/apache2
    container_name: isle-fedora-prodname # rename container to indicate type e.g. prod, stage, dev or version here and remove comment
    extra_hosts:
      - "isle-prod-site.institution:IP address of Dockerhost server" # edit here and remove comment


  solr:
    image: islandoracollabgroup/isle-solr:alpha2
    ports:
      - "8091:8080"
      - "8983:8983"
    tty: true
    volumes:
    - ./solr/tomcat/server.xml:/usr/local/tomcat/conf/server.xml # edit for SSL additions
    - ./solr/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml # edit lines: 45 & 48 to add appropriate passwords
    - ./solr/solr/solr.xml:/usr/local/tomcat/conf/Catalina/localhost/solr.xml
    - ./solr/solr/solrconfig.xml:/usr/local/solr/collection1/conf/solrconfig.xml # edit all appropriate lines for any customizations or merges from production settings.
    - ./solr/solr/schema.xml:/usr/local/solr/collection1/conf/schema.xml # edit all appropriate lines for any customizations or merges from production settings.
    - ./solr/solr/stopwords.txt:/usr/local/solr/collection1/conf/stopwords.txt # edit all appropriate lines for any customizations or merges from production settings.
    - ./isle_production_data_storage/data/solr:/usr/local/solr/collection1/data
    - ./isle_production_data_storage/data/solr/log/tomcat:/usr/local/tomcat/logs
    container_name: isle-solr-prodname # rename container to indicate type e.g. prod, stage, dev or version here and remove comment

  apache:
    image: islandoracollabgroup/isle-apache:alpha2
    ports:
      - "80:80"
      - "443:443"
    tty: true
    depends_on:
      - mysql
      - fedora
    volumes:
      - ./apache/site.conf:/etc/apache2/sites-available/site.conf # make edits as necessary
      - ./apache/settings.php:/var/www/html/sites/default/settings.php # make edits as necessary
      - ./isle_production_data_storage/data/apache/html:/var/www/html #this is current production code with any previous settings.php files removed
      - ./isle_production_data_storage/data/apache/log:/var/log/apache2
    container_name: isle-apache-prodname # rename container to indicate type e.g. prod, stage, dev or version here and remove comment
    extra_hosts:
      - "isle-prod-site.institution:IP address of Dockerhost server" # edit here and remove comment
